name: movi3s_plus
description: "A new Flutter project."
publish_to: "none"
version: 0.1.0

environment:
  sdk: ^3.7.0

dependencies:
  dio: ^5.8.0+1
  flex_color_scheme: ^8.1.1
  flutter:
    sdk: flutter
  flutter_dotenv: ^5.2.1
  google_fonts: ^6.2.1
  provider: ^6.1.2
  sizer: ^3.0.5
  animated_toggle_switch: ^0.8.4

dev_dependencies:
  flutter_lints: ^5.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - .env
